import numpy as np
import matplotlib.pyplot as plt
from conduction_part2 import *
a_cuivre=114E-6
a_verre=0.58E-6
abscisse=np.array([0.01*i for i in range(101)])
# question e
# pour le cuivre
tfcuivre2,tcuivre2,Tcuivre2=conduction2(a_cuivre,5.)
tfcuivre3,tcuivre3,Tcuivre3=conduction2(a_cuivre,0.3)
# pour le verre
tfverre2,tverre2,Tverre2=conduction2(a_verre,5.)
tfverre3,tverre3,Tverre3=conduction2(a_verre,0.3)
print('temps mis pour atteindre la stationnarité pour le cuivre avec un pas de temps de 5 secondes=',tfcuivre2,'secondes')
print('temps mis pour atteindre la stationnarité pour le cuivre avec un pas de temps de 0.3 seconde=',tfcuivre3,'secondes')
print('temps mis pour atteindre la stationnarité pour le verre avec un pas de temps de 5 secondes=',tfverre2,'secondes')
print('temps mis pour atteindre la stationnarité pour le verre avec un pas de temps de 0.3 seconde=',tfverre3,'secondes')
#
plt.figure('figure eii')
plt.title("Température d'équilibre d'une barre de 1 m")
plt.plot(abscisse,Tverre2[-1,:],'r',label="verre dt=5s")
plt.plot(abscisse,Tverre3[-1,:],'r+',label="verre dt=0.3s")
#plt.plot(abscisse,Tcuivre2[-1,:],'b+',label="cuivre dt=5s")
plt.plot(abscisse,Tcuivre3[-1,:],'bs',label="cuivre dt=0.3s")
plt.xlabel('longueur de la barre en mètre')
plt.ylabel('température en °C')
plt.legend()
plt.show()
plt.savefig('figure_eii.png')
#
plt.figure('figure eiii')
plt.title("Evolution de la température du milieu de la barre au cours du temps")
plt.plot(tverre2,Tverre2[:,49],'r',label="verre dt=5s")
plt.plot(tverre3,Tverre3[:,49],'r+',label="verre dt=0.3s")
#plt.plot(tcuivre2,Tcuivre2[:,49],'b+',label="cuivre dt=5s")
plt.plot(tcuivre3,Tcuivre3[:,49],'bs',label="cuivre dt=0.3s")
plt.xlabel('temps en secondes')
plt.ylabel('température en °C')
plt.legend()
plt.show()
plt.savefig('figure_eiii.png')
#
plt.figure('figure eiv1')
plt.title("Evolution de la température de la barre de cuivre dt=5s")
tcuivre2=tcuivre2/(60.*60.)
plt.pcolor(abscisse,tcuivre2,Tcuivre2)
plt.ylabel('temps en heures')
plt.xlabel('longueur de la barre en mètre')
cbar=plt.colorbar()
cbar.set_label('Température en °C')
plt.show()
plt.savefig('figure_eiv_cuivre_5s.png')
#
plt.figure('figure eiv2')
plt.title("Evolution de la température de la barre de verre dt=5s")
tverre2=tverre2/(60.*60.)
plt.pcolor(abscisse,tverre2,Tverre2)
plt.ylabel('temps en heures')
plt.xlabel('longueur de la barre en mètre')
cbar=plt.colorbar()
cbar.set_label('Température en °C')
plt.show()
plt.savefig('figure_eiv_verre_5s.png')
#
plt.figure('figure eiv11')
plt.title("Evolution de la température de la barre de cuivre dt=0.3s")
tcuivre3=tcuivre3/(60.*60.)
plt.pcolor(abscisse,tcuivre3,Tcuivre3)
plt.ylabel('temps en heures')
plt.xlabel('longueur de la barre en mètre')
cbar=plt.colorbar()
cbar.set_label('Température en °C')
plt.show()
plt.savefig('figure_eiv_cuivre_03s.png')
#
plt.figure('figure eiv22')
plt.title("Evolution de la température de la barre de verre dt=0.3s")
tverre3=tverre3/(60.*60.)
plt.pcolor(abscisse,tverre3,Tverre3)
plt.ylabel('temps en heures')
plt.xlabel('longueur de la barre en mètre')
cbar=plt.colorbar()
cbar.set_label('Température en °C')
plt.show()
plt.savefig('figure_eiv_verre_03s.png')